
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TimeSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TimeSession
 * 
 */
export type TimeSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$TimeSessionPayload>

export type AggregateTimeSession = {
  _count: TimeSessionCountAggregateOutputType | null
  _avg: TimeSessionAvgAggregateOutputType | null
  _sum: TimeSessionSumAggregateOutputType | null
  _min: TimeSessionMinAggregateOutputType | null
  _max: TimeSessionMaxAggregateOutputType | null
}

export type TimeSessionAvgAggregateOutputType = {
  durationSeconds: number | null
}

export type TimeSessionSumAggregateOutputType = {
  durationSeconds: number | null
}

export type TimeSessionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  taskId: string | null
  status: $Enums.TimeSessionStatus | null
  startedAt: Date | null
  pausedAt: Date | null
  endedAt: Date | null
  durationSeconds: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TimeSessionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  taskId: string | null
  status: $Enums.TimeSessionStatus | null
  startedAt: Date | null
  pausedAt: Date | null
  endedAt: Date | null
  durationSeconds: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TimeSessionCountAggregateOutputType = {
  id: number
  userId: number
  taskId: number
  status: number
  startedAt: number
  pausedAt: number
  endedAt: number
  durationSeconds: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TimeSessionAvgAggregateInputType = {
  durationSeconds?: true
}

export type TimeSessionSumAggregateInputType = {
  durationSeconds?: true
}

export type TimeSessionMinAggregateInputType = {
  id?: true
  userId?: true
  taskId?: true
  status?: true
  startedAt?: true
  pausedAt?: true
  endedAt?: true
  durationSeconds?: true
  createdAt?: true
  updatedAt?: true
}

export type TimeSessionMaxAggregateInputType = {
  id?: true
  userId?: true
  taskId?: true
  status?: true
  startedAt?: true
  pausedAt?: true
  endedAt?: true
  durationSeconds?: true
  createdAt?: true
  updatedAt?: true
}

export type TimeSessionCountAggregateInputType = {
  id?: true
  userId?: true
  taskId?: true
  status?: true
  startedAt?: true
  pausedAt?: true
  endedAt?: true
  durationSeconds?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TimeSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeSession to aggregate.
   */
  where?: Prisma.TimeSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSessions to fetch.
   */
  orderBy?: Prisma.TimeSessionOrderByWithRelationInput | Prisma.TimeSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TimeSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TimeSessions
  **/
  _count?: true | TimeSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TimeSessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TimeSessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TimeSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TimeSessionMaxAggregateInputType
}

export type GetTimeSessionAggregateType<T extends TimeSessionAggregateArgs> = {
      [P in keyof T & keyof AggregateTimeSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTimeSession[P]>
    : Prisma.GetScalarType<T[P], AggregateTimeSession[P]>
}




export type TimeSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeSessionWhereInput
  orderBy?: Prisma.TimeSessionOrderByWithAggregationInput | Prisma.TimeSessionOrderByWithAggregationInput[]
  by: Prisma.TimeSessionScalarFieldEnum[] | Prisma.TimeSessionScalarFieldEnum
  having?: Prisma.TimeSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TimeSessionCountAggregateInputType | true
  _avg?: TimeSessionAvgAggregateInputType
  _sum?: TimeSessionSumAggregateInputType
  _min?: TimeSessionMinAggregateInputType
  _max?: TimeSessionMaxAggregateInputType
}

export type TimeSessionGroupByOutputType = {
  id: string
  userId: string
  taskId: string
  status: $Enums.TimeSessionStatus
  startedAt: Date
  pausedAt: Date | null
  endedAt: Date | null
  durationSeconds: number
  createdAt: Date
  updatedAt: Date
  _count: TimeSessionCountAggregateOutputType | null
  _avg: TimeSessionAvgAggregateOutputType | null
  _sum: TimeSessionSumAggregateOutputType | null
  _min: TimeSessionMinAggregateOutputType | null
  _max: TimeSessionMaxAggregateOutputType | null
}

export type GetTimeSessionGroupByPayload<T extends TimeSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TimeSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TimeSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TimeSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TimeSessionGroupByOutputType[P]>
      }
    >
  >



export type TimeSessionWhereInput = {
  AND?: Prisma.TimeSessionWhereInput | Prisma.TimeSessionWhereInput[]
  OR?: Prisma.TimeSessionWhereInput[]
  NOT?: Prisma.TimeSessionWhereInput | Prisma.TimeSessionWhereInput[]
  id?: Prisma.StringFilter<"TimeSession"> | string
  userId?: Prisma.StringFilter<"TimeSession"> | string
  taskId?: Prisma.StringFilter<"TimeSession"> | string
  status?: Prisma.EnumTimeSessionStatusFilter<"TimeSession"> | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  pausedAt?: Prisma.DateTimeNullableFilter<"TimeSession"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableFilter<"TimeSession"> | Date | string | null
  durationSeconds?: Prisma.IntFilter<"TimeSession"> | number
  createdAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}

export type TimeSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  pausedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  task?: Prisma.TaskOrderByWithRelationInput
}

export type TimeSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TimeSessionWhereInput | Prisma.TimeSessionWhereInput[]
  OR?: Prisma.TimeSessionWhereInput[]
  NOT?: Prisma.TimeSessionWhereInput | Prisma.TimeSessionWhereInput[]
  userId?: Prisma.StringFilter<"TimeSession"> | string
  taskId?: Prisma.StringFilter<"TimeSession"> | string
  status?: Prisma.EnumTimeSessionStatusFilter<"TimeSession"> | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  pausedAt?: Prisma.DateTimeNullableFilter<"TimeSession"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableFilter<"TimeSession"> | Date | string | null
  durationSeconds?: Prisma.IntFilter<"TimeSession"> | number
  createdAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}, "id">

export type TimeSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  pausedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TimeSessionCountOrderByAggregateInput
  _avg?: Prisma.TimeSessionAvgOrderByAggregateInput
  _max?: Prisma.TimeSessionMaxOrderByAggregateInput
  _min?: Prisma.TimeSessionMinOrderByAggregateInput
  _sum?: Prisma.TimeSessionSumOrderByAggregateInput
}

export type TimeSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.TimeSessionScalarWhereWithAggregatesInput | Prisma.TimeSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.TimeSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TimeSessionScalarWhereWithAggregatesInput | Prisma.TimeSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TimeSession"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TimeSession"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"TimeSession"> | string
  status?: Prisma.EnumTimeSessionStatusWithAggregatesFilter<"TimeSession"> | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"TimeSession"> | Date | string
  pausedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TimeSession"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TimeSession"> | Date | string | null
  durationSeconds?: Prisma.IntWithAggregatesFilter<"TimeSession"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TimeSession"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TimeSession"> | Date | string
}

export type TimeSessionCreateInput = {
  id?: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTimeSessionsInput
  task: Prisma.TaskCreateNestedOneWithoutTimeSessionsInput
}

export type TimeSessionUncheckedCreateInput = {
  id?: string
  userId: string
  taskId: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTimeSessionsNestedInput
  task?: Prisma.TaskUpdateOneRequiredWithoutTimeSessionsNestedInput
}

export type TimeSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSessionCreateManyInput = {
  id?: string
  userId: string
  taskId: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSessionListRelationFilter = {
  every?: Prisma.TimeSessionWhereInput
  some?: Prisma.TimeSessionWhereInput
  none?: Prisma.TimeSessionWhereInput
}

export type TimeSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TimeSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  pausedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeSessionAvgOrderByAggregateInput = {
  durationSeconds?: Prisma.SortOrder
}

export type TimeSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  pausedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  pausedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeSessionSumOrderByAggregateInput = {
  durationSeconds?: Prisma.SortOrder
}

export type TimeSessionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutUserInput, Prisma.TimeSessionUncheckedCreateWithoutUserInput> | Prisma.TimeSessionCreateWithoutUserInput[] | Prisma.TimeSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutUserInput | Prisma.TimeSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TimeSessionCreateManyUserInputEnvelope
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
}

export type TimeSessionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutUserInput, Prisma.TimeSessionUncheckedCreateWithoutUserInput> | Prisma.TimeSessionCreateWithoutUserInput[] | Prisma.TimeSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutUserInput | Prisma.TimeSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TimeSessionCreateManyUserInputEnvelope
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
}

export type TimeSessionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutUserInput, Prisma.TimeSessionUncheckedCreateWithoutUserInput> | Prisma.TimeSessionCreateWithoutUserInput[] | Prisma.TimeSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutUserInput | Prisma.TimeSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TimeSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.TimeSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TimeSessionCreateManyUserInputEnvelope
  set?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  disconnect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  delete?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  update?: Prisma.TimeSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.TimeSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TimeSessionUpdateManyWithWhereWithoutUserInput | Prisma.TimeSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TimeSessionScalarWhereInput | Prisma.TimeSessionScalarWhereInput[]
}

export type TimeSessionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutUserInput, Prisma.TimeSessionUncheckedCreateWithoutUserInput> | Prisma.TimeSessionCreateWithoutUserInput[] | Prisma.TimeSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutUserInput | Prisma.TimeSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TimeSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.TimeSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TimeSessionCreateManyUserInputEnvelope
  set?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  disconnect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  delete?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  update?: Prisma.TimeSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.TimeSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TimeSessionUpdateManyWithWhereWithoutUserInput | Prisma.TimeSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TimeSessionScalarWhereInput | Prisma.TimeSessionScalarWhereInput[]
}

export type TimeSessionCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutTaskInput, Prisma.TimeSessionUncheckedCreateWithoutTaskInput> | Prisma.TimeSessionCreateWithoutTaskInput[] | Prisma.TimeSessionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutTaskInput | Prisma.TimeSessionCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TimeSessionCreateManyTaskInputEnvelope
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
}

export type TimeSessionUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutTaskInput, Prisma.TimeSessionUncheckedCreateWithoutTaskInput> | Prisma.TimeSessionCreateWithoutTaskInput[] | Prisma.TimeSessionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutTaskInput | Prisma.TimeSessionCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TimeSessionCreateManyTaskInputEnvelope
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
}

export type TimeSessionUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutTaskInput, Prisma.TimeSessionUncheckedCreateWithoutTaskInput> | Prisma.TimeSessionCreateWithoutTaskInput[] | Prisma.TimeSessionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutTaskInput | Prisma.TimeSessionCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TimeSessionUpsertWithWhereUniqueWithoutTaskInput | Prisma.TimeSessionUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TimeSessionCreateManyTaskInputEnvelope
  set?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  disconnect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  delete?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  update?: Prisma.TimeSessionUpdateWithWhereUniqueWithoutTaskInput | Prisma.TimeSessionUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TimeSessionUpdateManyWithWhereWithoutTaskInput | Prisma.TimeSessionUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TimeSessionScalarWhereInput | Prisma.TimeSessionScalarWhereInput[]
}

export type TimeSessionUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TimeSessionCreateWithoutTaskInput, Prisma.TimeSessionUncheckedCreateWithoutTaskInput> | Prisma.TimeSessionCreateWithoutTaskInput[] | Prisma.TimeSessionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TimeSessionCreateOrConnectWithoutTaskInput | Prisma.TimeSessionCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TimeSessionUpsertWithWhereUniqueWithoutTaskInput | Prisma.TimeSessionUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TimeSessionCreateManyTaskInputEnvelope
  set?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  disconnect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  delete?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  connect?: Prisma.TimeSessionWhereUniqueInput | Prisma.TimeSessionWhereUniqueInput[]
  update?: Prisma.TimeSessionUpdateWithWhereUniqueWithoutTaskInput | Prisma.TimeSessionUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TimeSessionUpdateManyWithWhereWithoutTaskInput | Prisma.TimeSessionUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TimeSessionScalarWhereInput | Prisma.TimeSessionScalarWhereInput[]
}

export type EnumTimeSessionStatusFieldUpdateOperationsInput = {
  set?: $Enums.TimeSessionStatus
}

export type TimeSessionCreateWithoutUserInput = {
  id?: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutTimeSessionsInput
}

export type TimeSessionUncheckedCreateWithoutUserInput = {
  id?: string
  taskId: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSessionCreateOrConnectWithoutUserInput = {
  where: Prisma.TimeSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeSessionCreateWithoutUserInput, Prisma.TimeSessionUncheckedCreateWithoutUserInput>
}

export type TimeSessionCreateManyUserInputEnvelope = {
  data: Prisma.TimeSessionCreateManyUserInput | Prisma.TimeSessionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TimeSessionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TimeSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeSessionUpdateWithoutUserInput, Prisma.TimeSessionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TimeSessionCreateWithoutUserInput, Prisma.TimeSessionUncheckedCreateWithoutUserInput>
}

export type TimeSessionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TimeSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeSessionUpdateWithoutUserInput, Prisma.TimeSessionUncheckedUpdateWithoutUserInput>
}

export type TimeSessionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TimeSessionScalarWhereInput
  data: Prisma.XOR<Prisma.TimeSessionUpdateManyMutationInput, Prisma.TimeSessionUncheckedUpdateManyWithoutUserInput>
}

export type TimeSessionScalarWhereInput = {
  AND?: Prisma.TimeSessionScalarWhereInput | Prisma.TimeSessionScalarWhereInput[]
  OR?: Prisma.TimeSessionScalarWhereInput[]
  NOT?: Prisma.TimeSessionScalarWhereInput | Prisma.TimeSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"TimeSession"> | string
  userId?: Prisma.StringFilter<"TimeSession"> | string
  taskId?: Prisma.StringFilter<"TimeSession"> | string
  status?: Prisma.EnumTimeSessionStatusFilter<"TimeSession"> | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  pausedAt?: Prisma.DateTimeNullableFilter<"TimeSession"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableFilter<"TimeSession"> | Date | string | null
  durationSeconds?: Prisma.IntFilter<"TimeSession"> | number
  createdAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TimeSession"> | Date | string
}

export type TimeSessionCreateWithoutTaskInput = {
  id?: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTimeSessionsInput
}

export type TimeSessionUncheckedCreateWithoutTaskInput = {
  id?: string
  userId: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSessionCreateOrConnectWithoutTaskInput = {
  where: Prisma.TimeSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeSessionCreateWithoutTaskInput, Prisma.TimeSessionUncheckedCreateWithoutTaskInput>
}

export type TimeSessionCreateManyTaskInputEnvelope = {
  data: Prisma.TimeSessionCreateManyTaskInput | Prisma.TimeSessionCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type TimeSessionUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TimeSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeSessionUpdateWithoutTaskInput, Prisma.TimeSessionUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.TimeSessionCreateWithoutTaskInput, Prisma.TimeSessionUncheckedCreateWithoutTaskInput>
}

export type TimeSessionUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TimeSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeSessionUpdateWithoutTaskInput, Prisma.TimeSessionUncheckedUpdateWithoutTaskInput>
}

export type TimeSessionUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.TimeSessionScalarWhereInput
  data: Prisma.XOR<Prisma.TimeSessionUpdateManyMutationInput, Prisma.TimeSessionUncheckedUpdateManyWithoutTaskInput>
}

export type TimeSessionCreateManyUserInput = {
  id?: string
  taskId: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSessionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutTimeSessionsNestedInput
}

export type TimeSessionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSessionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSessionCreateManyTaskInput = {
  id?: string
  userId: string
  status?: $Enums.TimeSessionStatus
  startedAt?: Date | string
  pausedAt?: Date | string | null
  endedAt?: Date | string | null
  durationSeconds?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeSessionUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTimeSessionsNestedInput
}

export type TimeSessionUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeSessionUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTimeSessionStatusFieldUpdateOperationsInput | $Enums.TimeSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pausedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TimeSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  startedAt?: boolean
  pausedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timeSession"]>

export type TimeSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  startedAt?: boolean
  pausedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timeSession"]>

export type TimeSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  startedAt?: boolean
  pausedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timeSession"]>

export type TimeSessionSelectScalar = {
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  startedAt?: boolean
  pausedAt?: boolean
  endedAt?: boolean
  durationSeconds?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TimeSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "taskId" | "status" | "startedAt" | "pausedAt" | "endedAt" | "durationSeconds" | "createdAt" | "updatedAt", ExtArgs["result"]["timeSession"]>
export type TimeSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type TimeSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type TimeSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}

export type $TimeSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TimeSession"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    task: Prisma.$TaskPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    taskId: string
    status: $Enums.TimeSessionStatus
    startedAt: Date
    pausedAt: Date | null
    endedAt: Date | null
    durationSeconds: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["timeSession"]>
  composites: {}
}

export type TimeSessionGetPayload<S extends boolean | null | undefined | TimeSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload, S>

export type TimeSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TimeSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TimeSessionCountAggregateInputType | true
  }

export interface TimeSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TimeSession'], meta: { name: 'TimeSession' } }
  /**
   * Find zero or one TimeSession that matches the filter.
   * @param {TimeSessionFindUniqueArgs} args - Arguments to find a TimeSession
   * @example
   * // Get one TimeSession
   * const timeSession = await prisma.timeSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TimeSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, TimeSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TimeSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TimeSessionFindUniqueOrThrowArgs} args - Arguments to find a TimeSession
   * @example
   * // Get one TimeSession
   * const timeSession = await prisma.timeSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TimeSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TimeSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSessionFindFirstArgs} args - Arguments to find a TimeSession
   * @example
   * // Get one TimeSession
   * const timeSession = await prisma.timeSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TimeSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, TimeSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSessionFindFirstOrThrowArgs} args - Arguments to find a TimeSession
   * @example
   * // Get one TimeSession
   * const timeSession = await prisma.timeSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TimeSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TimeSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TimeSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TimeSessions
   * const timeSessions = await prisma.timeSession.findMany()
   * 
   * // Get first 10 TimeSessions
   * const timeSessions = await prisma.timeSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const timeSessionWithIdOnly = await prisma.timeSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TimeSessionFindManyArgs>(args?: Prisma.SelectSubset<T, TimeSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TimeSession.
   * @param {TimeSessionCreateArgs} args - Arguments to create a TimeSession.
   * @example
   * // Create one TimeSession
   * const TimeSession = await prisma.timeSession.create({
   *   data: {
   *     // ... data to create a TimeSession
   *   }
   * })
   * 
   */
  create<T extends TimeSessionCreateArgs>(args: Prisma.SelectSubset<T, TimeSessionCreateArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TimeSessions.
   * @param {TimeSessionCreateManyArgs} args - Arguments to create many TimeSessions.
   * @example
   * // Create many TimeSessions
   * const timeSession = await prisma.timeSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TimeSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, TimeSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TimeSessions and returns the data saved in the database.
   * @param {TimeSessionCreateManyAndReturnArgs} args - Arguments to create many TimeSessions.
   * @example
   * // Create many TimeSessions
   * const timeSession = await prisma.timeSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TimeSessions and only return the `id`
   * const timeSessionWithIdOnly = await prisma.timeSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TimeSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TimeSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TimeSession.
   * @param {TimeSessionDeleteArgs} args - Arguments to delete one TimeSession.
   * @example
   * // Delete one TimeSession
   * const TimeSession = await prisma.timeSession.delete({
   *   where: {
   *     // ... filter to delete one TimeSession
   *   }
   * })
   * 
   */
  delete<T extends TimeSessionDeleteArgs>(args: Prisma.SelectSubset<T, TimeSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TimeSession.
   * @param {TimeSessionUpdateArgs} args - Arguments to update one TimeSession.
   * @example
   * // Update one TimeSession
   * const timeSession = await prisma.timeSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TimeSessionUpdateArgs>(args: Prisma.SelectSubset<T, TimeSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TimeSessions.
   * @param {TimeSessionDeleteManyArgs} args - Arguments to filter TimeSessions to delete.
   * @example
   * // Delete a few TimeSessions
   * const { count } = await prisma.timeSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TimeSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, TimeSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimeSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TimeSessions
   * const timeSession = await prisma.timeSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TimeSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, TimeSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimeSessions and returns the data updated in the database.
   * @param {TimeSessionUpdateManyAndReturnArgs} args - Arguments to update many TimeSessions.
   * @example
   * // Update many TimeSessions
   * const timeSession = await prisma.timeSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TimeSessions and only return the `id`
   * const timeSessionWithIdOnly = await prisma.timeSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TimeSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TimeSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TimeSession.
   * @param {TimeSessionUpsertArgs} args - Arguments to update or create a TimeSession.
   * @example
   * // Update or create a TimeSession
   * const timeSession = await prisma.timeSession.upsert({
   *   create: {
   *     // ... data to create a TimeSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TimeSession we want to update
   *   }
   * })
   */
  upsert<T extends TimeSessionUpsertArgs>(args: Prisma.SelectSubset<T, TimeSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__TimeSessionClient<runtime.Types.Result.GetResult<Prisma.$TimeSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TimeSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSessionCountArgs} args - Arguments to filter TimeSessions to count.
   * @example
   * // Count the number of TimeSessions
   * const count = await prisma.timeSession.count({
   *   where: {
   *     // ... the filter for the TimeSessions we want to count
   *   }
   * })
  **/
  count<T extends TimeSessionCountArgs>(
    args?: Prisma.Subset<T, TimeSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TimeSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TimeSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TimeSessionAggregateArgs>(args: Prisma.Subset<T, TimeSessionAggregateArgs>): Prisma.PrismaPromise<GetTimeSessionAggregateType<T>>

  /**
   * Group by TimeSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TimeSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TimeSessionGroupByArgs['orderBy'] }
      : { orderBy?: TimeSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TimeSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTimeSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TimeSession model
 */
readonly fields: TimeSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TimeSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TimeSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TimeSession model
 */
export interface TimeSessionFieldRefs {
  readonly id: Prisma.FieldRef<"TimeSession", 'String'>
  readonly userId: Prisma.FieldRef<"TimeSession", 'String'>
  readonly taskId: Prisma.FieldRef<"TimeSession", 'String'>
  readonly status: Prisma.FieldRef<"TimeSession", 'TimeSessionStatus'>
  readonly startedAt: Prisma.FieldRef<"TimeSession", 'DateTime'>
  readonly pausedAt: Prisma.FieldRef<"TimeSession", 'DateTime'>
  readonly endedAt: Prisma.FieldRef<"TimeSession", 'DateTime'>
  readonly durationSeconds: Prisma.FieldRef<"TimeSession", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TimeSession", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TimeSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TimeSession findUnique
 */
export type TimeSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * Filter, which TimeSession to fetch.
   */
  where: Prisma.TimeSessionWhereUniqueInput
}

/**
 * TimeSession findUniqueOrThrow
 */
export type TimeSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * Filter, which TimeSession to fetch.
   */
  where: Prisma.TimeSessionWhereUniqueInput
}

/**
 * TimeSession findFirst
 */
export type TimeSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * Filter, which TimeSession to fetch.
   */
  where?: Prisma.TimeSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSessions to fetch.
   */
  orderBy?: Prisma.TimeSessionOrderByWithRelationInput | Prisma.TimeSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeSessions.
   */
  cursor?: Prisma.TimeSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeSessions.
   */
  distinct?: Prisma.TimeSessionScalarFieldEnum | Prisma.TimeSessionScalarFieldEnum[]
}

/**
 * TimeSession findFirstOrThrow
 */
export type TimeSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * Filter, which TimeSession to fetch.
   */
  where?: Prisma.TimeSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSessions to fetch.
   */
  orderBy?: Prisma.TimeSessionOrderByWithRelationInput | Prisma.TimeSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeSessions.
   */
  cursor?: Prisma.TimeSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeSessions.
   */
  distinct?: Prisma.TimeSessionScalarFieldEnum | Prisma.TimeSessionScalarFieldEnum[]
}

/**
 * TimeSession findMany
 */
export type TimeSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * Filter, which TimeSessions to fetch.
   */
  where?: Prisma.TimeSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeSessions to fetch.
   */
  orderBy?: Prisma.TimeSessionOrderByWithRelationInput | Prisma.TimeSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TimeSessions.
   */
  cursor?: Prisma.TimeSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeSessions.
   */
  distinct?: Prisma.TimeSessionScalarFieldEnum | Prisma.TimeSessionScalarFieldEnum[]
}

/**
 * TimeSession create
 */
export type TimeSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a TimeSession.
   */
  data: Prisma.XOR<Prisma.TimeSessionCreateInput, Prisma.TimeSessionUncheckedCreateInput>
}

/**
 * TimeSession createMany
 */
export type TimeSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TimeSessions.
   */
  data: Prisma.TimeSessionCreateManyInput | Prisma.TimeSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TimeSession createManyAndReturn
 */
export type TimeSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * The data used to create many TimeSessions.
   */
  data: Prisma.TimeSessionCreateManyInput | Prisma.TimeSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TimeSession update
 */
export type TimeSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a TimeSession.
   */
  data: Prisma.XOR<Prisma.TimeSessionUpdateInput, Prisma.TimeSessionUncheckedUpdateInput>
  /**
   * Choose, which TimeSession to update.
   */
  where: Prisma.TimeSessionWhereUniqueInput
}

/**
 * TimeSession updateMany
 */
export type TimeSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TimeSessions.
   */
  data: Prisma.XOR<Prisma.TimeSessionUpdateManyMutationInput, Prisma.TimeSessionUncheckedUpdateManyInput>
  /**
   * Filter which TimeSessions to update
   */
  where?: Prisma.TimeSessionWhereInput
  /**
   * Limit how many TimeSessions to update.
   */
  limit?: number
}

/**
 * TimeSession updateManyAndReturn
 */
export type TimeSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * The data used to update TimeSessions.
   */
  data: Prisma.XOR<Prisma.TimeSessionUpdateManyMutationInput, Prisma.TimeSessionUncheckedUpdateManyInput>
  /**
   * Filter which TimeSessions to update
   */
  where?: Prisma.TimeSessionWhereInput
  /**
   * Limit how many TimeSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TimeSession upsert
 */
export type TimeSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the TimeSession to update in case it exists.
   */
  where: Prisma.TimeSessionWhereUniqueInput
  /**
   * In case the TimeSession found by the `where` argument doesn't exist, create a new TimeSession with this data.
   */
  create: Prisma.XOR<Prisma.TimeSessionCreateInput, Prisma.TimeSessionUncheckedCreateInput>
  /**
   * In case the TimeSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TimeSessionUpdateInput, Prisma.TimeSessionUncheckedUpdateInput>
}

/**
 * TimeSession delete
 */
export type TimeSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
  /**
   * Filter which TimeSession to delete.
   */
  where: Prisma.TimeSessionWhereUniqueInput
}

/**
 * TimeSession deleteMany
 */
export type TimeSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeSessions to delete
   */
  where?: Prisma.TimeSessionWhereInput
  /**
   * Limit how many TimeSessions to delete.
   */
  limit?: number
}

/**
 * TimeSession without action
 */
export type TimeSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeSession
   */
  select?: Prisma.TimeSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeSession
   */
  omit?: Prisma.TimeSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeSessionInclude<ExtArgs> | null
}
