/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const Priority = {
  low: "low",
  medium: "medium",
  high: "high",
  critical: "critical",
} as const;

export type Priority = (typeof Priority)[keyof typeof Priority];

export const TaskStatus = {
  todo: "todo",
  in_progress: "in_progress",
  paused: "paused",
  done: "done",
  canceled: "canceled",
} as const;

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

export const TimeSessionStatus = {
  running: "running",
  paused: "paused",
  completed: "completed",
} as const;

export type TimeSessionStatus =
  (typeof TimeSessionStatus)[keyof typeof TimeSessionStatus];
